mysql-tripitaka:
  restart: always
  image: mysql
  volumes:
    - ./data/mysql/:/var/lib/mysql
    - ./conf/mysql/:/etc/mysql/conf.d
    - ./data/log/:/var/log/mysql
  ports:
    - "3307:3307"
  environment:
    - MYSQL_DATABASE=cutrect
    - MYSQL_ROOT_PASSWORD=root

redis-tripitaka:
  image: redis:latest
  ports:
    - "6378:6378"

nginx-tripitaka:
  restart: always
  image: nginx
  ports:
    - "8028:8028"
  volumes:
    - ./conf/nginx/tripitaka_nginx.conf:/etc/nginx/conf.d/tripitaka_nginx.conf
    - ./static/:/cutrect/static/
  volumes_from:
    - web_tripitaka
  links:
    - web_tripitaka:web_tripitaka

web_tripitaka:
  restart: always
  build: .
  ports:
    - "8000:8000"
  volumes:
    - .:/cutrect
    - ./../Z:/cutrect/frontend
  links:
    - mysql-tripitaka:mysql_tripitaka
  command: uwsgi -s :8000 -w cutrect.wsgi -p 3
  #depends_on:
  #  - mysql-tripitaka
  #  - redis-tripitaka



