# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 11:43
from __future__ import unicode_literals

import db_file_storage.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user_count', models.IntegerField()),
                ('view_count', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '访问记录',
                'verbose_name': '访问记录',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='批次名')),
                ('series', models.CharField(max_length=64, verbose_name='藏经版本名')),
                ('org', models.PositiveSmallIntegerField(choices=[(0, '阿里'), (1, '百度'), (2, '华南理工')], default=0, verbose_name='组织名称')),
                ('upload', models.FileField(null=True, upload_to='', verbose_name='上传批次数据')),
                ('submit_date', models.DateField(blank=True, null=True, verbose_name='提交时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'ordering': ('submit_date', 'name'),
                'verbose_name_plural': '批次管理',
                'verbose_name': '批次',
            },
        ),
        migrations.CreateModel(
            name='PageRect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page', models.CharField(max_length=64, null=True, verbose_name='关联页ID')),
                ('line_count', models.IntegerField(blank=True, null=True, verbose_name='最大行数')),
                ('column_count', models.IntegerField(blank=True, null=True, verbose_name='最大列数')),
                ('rect_set', models.TextField(blank=True, null=True, verbose_name='切字块数据集')),
                ('create_date', models.DateField(blank=True, null=True, verbose_name='创建时间')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagerects', to='rect.Batch', verbose_name='批次')),
            ],
            options={
                'ordering': ('create_date',),
                'verbose_name_plural': '源-切分页管理',
                'verbose_name': '源-切分页',
            },
        ),
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x', models.PositiveSmallIntegerField(default=0, verbose_name='X坐标')),
                ('y', models.PositiveSmallIntegerField(default=0, verbose_name='Y坐标')),
                ('w', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='宽度')),
                ('h', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='高度')),
                ('ln', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='行号')),
                ('cn', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='列号')),
                ('cc', models.FloatField(blank=True, db_index=True, default=1, null=True, verbose_name='置信度')),
                ('word', models.CharField(blank=True, db_index=True, default='', max_length=4, null=True, verbose_name='汉字')),
                ('wcc', models.FloatField(blank=True, db_index=True, default=1, null=True, verbose_name='文字置信度')),
                ('ts', models.CharField(blank=True, db_index=True, default='', max_length=4, null=True, verbose_name='标字')),
                ('ctxt', models.CharField(blank=True, default='', max_length=12, null=True, verbose_name='标字')),
                ('date', models.DateField(blank=True, null=True, verbose_name='最近处理时间')),
            ],
            options={
                'ordering': ('schedule', 'task', 'word'),
                'verbose_name_plural': 'Patch管理',
                'verbose_name': 'Patch',
            },
        ),
        migrations.CreateModel(
            name='Rect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x', models.PositiveSmallIntegerField(default=0, verbose_name='X坐标')),
                ('y', models.PositiveSmallIntegerField(default=0, verbose_name='Y坐标')),
                ('w', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='宽度')),
                ('h', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='高度')),
                ('ln', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='行号')),
                ('cn', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='列号')),
                ('cc', models.FloatField(blank=True, db_index=True, default=1, null=True, verbose_name='置信度')),
                ('word', models.CharField(blank=True, db_index=True, default='', max_length=4, null=True, verbose_name='汉字')),
                ('wcc', models.FloatField(blank=True, db_index=True, default=1, null=True, verbose_name='文字置信度')),
                ('ts', models.CharField(blank=True, db_index=True, default='', max_length=4, null=True, verbose_name='标字')),
                ('ctxt', models.CharField(blank=True, default='', max_length=12, null=True, verbose_name='标字')),
                ('inset', models.FileField(blank=True, help_text='嵌入临时截图', null=True, storage=db_file_storage.storage.DatabaseFileStorage(), upload_to='core.DBPicture/bytes/filename/mimetype')),
                ('s3_inset', models.FileField(blank=True, null=True, storage='storages.backends.s3boto.S3BotoStorage', upload_to='tripitaka/hans', verbose_name='s3地址')),
                ('page_rect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rects', to='rect.PageRect', verbose_name='源-切分页')),
            ],
            options={
                'ordering': ('word',),
                'verbose_name_plural': '源-切字块管理',
                'verbose_name': '源-切字块',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='切分计划名')),
                ('type', models.PositiveSmallIntegerField(choices=[(2, '置信度'), (1, '顺序校对'), (3, '聚类')], db_index=True, default=1, verbose_name='切分方式')),
                ('task_info', models.TextField(verbose_name='任务格式化描述')),
                ('user_group', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='分配组')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '未激活'), (1, '已激活'), (2, '已过期'), (3, '已作废'), (4, '已完成')], db_index=True, default=0, verbose_name='计划状态')),
                ('end_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='截止日期')),
                ('create_date', models.DateField(blank=True, null=True, verbose_name='创建日期')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='rect.Batch', verbose_name='批次')),
            ],
            options={
                'ordering': ('end_date', 'name', 'status'),
                'verbose_name_plural': '切分计划管理',
                'verbose_name': '切分计划',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=64, verbose_name='任务编号')),
                ('type', models.PositiveSmallIntegerField(choices=[(2, '置信度'), (1, '顺序校对'), (3, '聚类')], db_index=True, default=1, verbose_name='切分方式')),
                ('status', models.PositiveSmallIntegerField(choices=[(-1, '未领取'), (0, '已领取'), (1, '处理中'), (2, '已过期'), (3, '已作废'), (4, '已完成')], db_index=True, default=-1, verbose_name='任务状态')),
                ('date', models.DateField(null=True, verbose_name='最近处理时间')),
                ('rect_set', models.TextField(null=True, verbose_name='页切片数据')),
                ('data', models.TextField(null=True, verbose_name='附加数据')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='rect.Schedule', verbose_name='切分计划')),
            ],
            options={
                'ordering': ('schedule', 'number', 'status'),
                'verbose_name_plural': '切分任务管理',
                'verbose_name': '切分任务',
            },
        ),
        migrations.AddField(
            model_name='patch',
            name='rect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patches', to='rect.Rect', verbose_name='源-切字块数据'),
        ),
        migrations.AddField(
            model_name='patch',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patches', to='rect.Schedule', verbose_name='切分计划'),
        ),
        migrations.AddField(
            model_name='patch',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patches', to='rect.Task', verbose_name='切分任务'),
        ),
    ]
