# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rect', 'create_reel_statis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reel_task_statistical',
            options={'ordering': ('schedule', 'reel'), 'verbose_name': '实体卷任务统计', 'verbose_name_plural': '实体卷任务统计管理'},
        ),
        migrations.AlterModelOptions(
            name='schedule_task_statistical',
            options={'ordering': ('schedule',), 'verbose_name': '切分计划任务统计', 'verbose_name_plural': '切分计划任务统计管理'},
        ),
        migrations.RemoveField(
            model_name='page',
            name='column_ready',
        ),
        migrations.RemoveField(
            model_name='page',
            name='cut_ready',
        ),
        migrations.RemoveField(
            model_name='page',
            name='image_ready',
        ),
        migrations.RemoveField(
            model_name='page',
            name='image_upload',
        ),
        migrations.RemoveField(
            model_name='page',
            name='ready',
        ),
        migrations.RemoveField(
            model_name='page',
            name='txt_ready',
        ),
        migrations.AddField(
            model_name='page',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '初始化'), (1, '切分数据未上传'), (2, '数据解析失败'), (3, '图片不存在'), (4, '列图不存在'), (5, '列图坐标不存在'), (7, '已准备好')], db_index=True, default=0, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='reel',
            name='ready',
            field=models.BooleanField(db_index=True, default=False, verbose_name='已准备好'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_no',
            field=models.CharField(default='', help_text='PN日期序列', max_length=64, verbose_name='切分计划批次'),
        ),
    ]
