# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rect', '0001_pagerect_reel'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=models.CharField(blank=True, max_length=64, verbose_name='计划名称'),
        ),
    ]
