# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rect', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='task_info',
        ),
        migrations.AddField(
            model_name='schedule',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='计划格式化描述'),
        ),
        migrations.AddField(
            model_name='task',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='任务格式化描述'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '未激活'), (1, '已激活'), (2, '已过期'), (3, '已作废'), (4, '已完成')], db_index=True, default=1, verbose_name='计划状态'),
        ),
    ]
