# Generated by Django 2.0 on 2018-01-27 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rect', '0001_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absenttask',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absent_tasks', to='jwt_auth.Staff'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='jwt_auth.Staff'),
        ),
        migrations.AlterField(
            model_name='cctask',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cc_tasks', to='jwt_auth.Staff'),
        ),
        migrations.AlterField(
            model_name='classifytask',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classify_tasks', to='jwt_auth.Staff'),
        ),
        migrations.AlterField(
            model_name='deletioncheckitem',
            name='modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modify_deletions', to='jwt_auth.Staff', verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='deletioncheckitem',
            name='verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verify_deletions', to='jwt_auth.Staff', verbose_name='审定人'),
        ),
        migrations.AlterField(
            model_name='deltask',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='del_tasks', to='jwt_auth.Staff'),
        ),
        migrations.AlterField(
            model_name='page',
            name='reel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='rect.Reel'),
        ),
        migrations.AlterField(
            model_name='pagerect',
            name='reel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reels', to='rect.Reel'),
        ),
        migrations.AlterField(
            model_name='pagetask',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_tasks', to='jwt_auth.Staff'),
        ),
        migrations.AlterField(
            model_name='patch',
            name='modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modify_patches', to='jwt_auth.Staff', verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='patch',
            name='verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verify_patches', to='jwt_auth.Staff', verbose_name='审定人'),
        ),
        migrations.AlterField(
            model_name='rect',
            name='reel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rects', to='rect.Reel'),
        ),
        migrations.AlterField(
            model_name='reel_task_statistical',
            name='reel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reel_tasks_statis', to='rect.Reel'),
        ),
        migrations.AlterField(
            model_name='reviewtask',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_tasks', to='jwt_auth.Staff'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='reels',
            field=models.ManyToManyField(blank=True, limit_choices_to={'ready': True}, to='rect.Reel'),
        ),
        migrations.AlterField(
            model_name='sutra',
            name='tripitaka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sutras', to='rect.Tripitaka'),
        ),
    ]
