# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 13:15
from __future__ import unicode_literals

import db_file_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocolumn',
            name='s3_inset',
            field=models.FileField(blank=True, max_length=256, null=True, storage='storages.backends.s3boto.S3BotoStorage', upload_to='tripitaka/hans', verbose_name='s3地址'),
        ),
        migrations.AlterField(
            model_name='opage',
            name='s3_inset',
            field=models.FileField(blank=True, max_length=256, null=True, storage='storages.backends.s3boto.S3BotoStorage', upload_to='tripitaka/hans', verbose_name='s3地址'),
        ),
        migrations.AlterField(
            model_name='rect',
            name='inset',
            field=models.FileField(blank=True, help_text='嵌入临时截图', max_length=256, null=True, storage=db_file_storage.storage.DatabaseFileStorage(), upload_to='core.DBPicture/bytes/filename/mimetype'),
        ),
        migrations.AlterField(
            model_name='rect',
            name='s3_inset',
            field=models.FileField(blank=True, max_length=256, null=True, storage='storages.backends.s3boto.S3BotoStorage', upload_to='tripitaka/hans', verbose_name='s3地址'),
        ),
    ]
