# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opage',
            name='code',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='关联页ID'),
        ),
    ]
