# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rect', '0002_schedule_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('code', models.CharField(max_length=27, primary_key=True, serialize=False, verbose_name='节点代码')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rect.Node', verbose_name='父节点')),
            ],
            options={
                'verbose_name': '节点',
                'verbose_name_plural': '节点',
            },
        ),
    ]
