# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rect', '0002_auto_20171227_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagerect',
            options={'ordering': ('create_date',), 'verbose_name': '源页切分集', 'verbose_name_plural': '源页切分集管理'},
        ),
        migrations.RemoveField(
            model_name='rect',
            name='inset',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='user_group',
        ),
        migrations.AddField(
            model_name='pagerect',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagerects', to='rect.OPage', verbose_name='关联源页信息'),
        ),
        migrations.AddField(
            model_name='rect',
            name='pcode',
            field=models.CharField(max_length=64, null=True, verbose_name='关联源页CODE'),
        ),
        migrations.AlterField(
            model_name='cctask',
            name='ttype',
            field=models.PositiveSmallIntegerField(choices=[(2, '置信度'), (1, '顺序校对'), (3, '聚类'), (4, '差缺补漏')], db_index=True, default=1, verbose_name='切分方式'),
        ),
        migrations.AlterField(
            model_name='classifytask',
            name='ttype',
            field=models.PositiveSmallIntegerField(choices=[(2, '置信度'), (1, '顺序校对'), (3, '聚类'), (4, '差缺补漏')], db_index=True, default=1, verbose_name='切分方式'),
        ),
        migrations.AlterField(
            model_name='pagerect',
            name='code',
            field=models.CharField(max_length=64, null=True, verbose_name='关联源页CODE'),
        ),
        migrations.AlterField(
            model_name='pagetask',
            name='ttype',
            field=models.PositiveSmallIntegerField(choices=[(2, '置信度'), (1, '顺序校对'), (3, '聚类'), (4, '差缺补漏')], db_index=True, default=1, verbose_name='切分方式'),
        ),
        migrations.AlterField(
            model_name='rect',
            name='page_rect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rects', to='rect.PageRect', verbose_name='源页切分集'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(2, '置信度'), (1, '顺序校对'), (3, '聚类'), (4, '差缺补漏')], db_index=True, default=1, verbose_name='切分方式'),
        ),
    ]
