# Generated by Django 2.0 on 2018-01-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rect', '0002_auto_20180128_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='absenttask',
            name='obtain_date',
            field=models.DateField(null=True, verbose_name='领取时间'),
        ),
        migrations.AddField(
            model_name='cctask',
            name='obtain_date',
            field=models.DateField(null=True, verbose_name='领取时间'),
        ),
        migrations.AddField(
            model_name='classifytask',
            name='obtain_date',
            field=models.DateField(null=True, verbose_name='领取时间'),
        ),
        migrations.AddField(
            model_name='deltask',
            name='obtain_date',
            field=models.DateField(null=True, verbose_name='领取时间'),
        ),
        migrations.AddField(
            model_name='pagetask',
            name='obtain_date',
            field=models.DateField(null=True, verbose_name='领取时间'),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='obtain_date',
            field=models.DateField(null=True, verbose_name='领取时间'),
        ),
        migrations.AlterField(
            model_name='absenttask',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '未就绪'), (1, '未领取'), (2, '已过期'), (3, '已放弃'), (4, '加急'), (5, '处理中'), (7, '已完成'), (9, '已作废')], db_index=True, default=1, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='cctask',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '未就绪'), (1, '未领取'), (2, '已过期'), (3, '已放弃'), (4, '加急'), (5, '处理中'), (7, '已完成'), (9, '已作废')], db_index=True, default=1, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='classifytask',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '未就绪'), (1, '未领取'), (2, '已过期'), (3, '已放弃'), (4, '加急'), (5, '处理中'), (7, '已完成'), (9, '已作废')], db_index=True, default=1, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='deltask',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '未就绪'), (1, '未领取'), (2, '已过期'), (3, '已放弃'), (4, '加急'), (5, '处理中'), (7, '已完成'), (9, '已作废')], db_index=True, default=1, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='pagetask',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '未就绪'), (1, '未领取'), (2, '已过期'), (3, '已放弃'), (4, '加急'), (5, '处理中'), (7, '已完成'), (9, '已作废')], db_index=True, default=1, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='reviewtask',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '未就绪'), (1, '未领取'), (2, '已过期'), (3, '已放弃'), (4, '加急'), (5, '处理中'), (7, '已完成'), (9, '已作废')], db_index=True, default=1, verbose_name='任务状态'),
        ),
    ]
