# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rect', '0002_auto_20180111_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '初始化'), (1, '切分数据未上传'), (2, '数据解析失败'), (3, '字块数据未展开'), (4, '图片不存在'), (5, '列图不存在'), (6, '列图坐标不存在'), (7, '已准备好')], db_index=True, default=0, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='rect',
            name='page_code',
            field=models.CharField(db_index=True, max_length=23, verbose_name='关联源页CODE'),
        ),
    ]
