# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-24 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rect', '0003_auto_20171224_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='rect',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rects', to='rect.Batch', verbose_name='批次'),
        ),
    ]
