# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 02:38
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rect', '0003_auto_20180111_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='rect',
            name='column_set',
            field=jsonfield.fields.JSONField(default=list, verbose_name='切字块所在切列JSON数据集'),
        ),
    ]
