# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-24 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rect', '0004_rect_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagerect',
            name='page',
        ),
        migrations.AddField(
            model_name='pagerect',
            name='code',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='关联页ID'),
        ),
        migrations.AlterField(
            model_name='cctask',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '未领取'), (1, '已领取'), (2, '处理中'), (3, '已过期'), (4, '已作废'), (5, '已完成')], db_index=True, default=0, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='classifytask',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '未领取'), (1, '已领取'), (2, '处理中'), (3, '已过期'), (4, '已作废'), (5, '已完成')], db_index=True, default=0, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='pagetask',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '未领取'), (1, '已领取'), (2, '处理中'), (3, '已过期'), (4, '已作废'), (5, '已完成')], db_index=True, default=0, verbose_name='任务状态'),
        ),
    ]
