# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rect', '0004_rect_column_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '初始化'), (1, '切分数据未上传'), (2, '数据解析失败'), (3, '字块数据未展开'), (4, '图片不存在'), (5, '列图不存在'), (6, '列图坐标不存在'), (7, '字块对应列图未准备'), (8, '字块对应列图不存在'), (9, '已准备好'), (10, '已入卷标记')], db_index=True, default=0, verbose_name='操作类型'),
        ),
    ]
