# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rect', '0004_auto_20171230_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rect',
            name='status',
        ),
        migrations.AddField(
            model_name='rect',
            name='op',
            field=models.PositiveSmallIntegerField(db_index=True, default=1, verbose_name='操作类型'),
        ),
    ]
