# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rect', '0005_auto_20171231_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagerect',
            name='op',
            field=models.PositiveSmallIntegerField(db_index=True, default=1, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='pagerect',
            name='rect_set',
            field=models.TextField(blank=True, null=True, verbose_name='切字块JSON数据集'),
        ),
    ]
