# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-03 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rect', '0006_auto_20171231_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rect',
            old_name='ln',
            new_name='line_no',
        ),
        migrations.RemoveField(
            model_name='rect',
            name='cn',
        ),
        migrations.RemoveField(
            model_name='rect',
            name='wcc',
        ),
        migrations.RemoveField(
            model_name='rect',
            name='word',
        ),
        migrations.AddField(
            model_name='rect',
            name='c_conf',
            field=models.FloatField(blank=True, db_index=True, default=1, null=True, verbose_name='识别置信度'),
        ),
        migrations.AddField(
            model_name='rect',
            name='ch',
            field=models.CharField(blank=True, db_index=True, default='', max_length=2, null=True, verbose_name='文字'),
        ),
        migrations.AddField(
            model_name='rect',
            name='char_no',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='字号'),
        ),
        migrations.AddField(
            model_name='rect',
            name='cid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40, null=True, verbose_name='经字号'),
        ),
        migrations.AddField(
            model_name='rect',
            name='page_no',
            field=models.CharField(blank=True, db_index=True, default='', max_length=4, null=True, verbose_name='页序号'),
        ),
        migrations.AddField(
            model_name='rect',
            name='reel_no',
            field=models.CharField(blank=True, db_index=True, default='', max_length=3, null=True, verbose_name='卷序号'),
        ),
        migrations.AddField(
            model_name='rect',
            name='sutra_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=8, null=True, verbose_name='经号'),
        ),
        migrations.AddField(
            model_name='rect',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='rect',
            name='vol_no',
            field=models.CharField(blank=True, db_index=True, default='', max_length=3, null=True, verbose_name='册序号'),
        ),
        migrations.AlterField(
            model_name='rect',
            name='ts',
            field=models.CharField(blank=True, db_index=True, default='', max_length=2, null=True, verbose_name='标字'),
        ),
    ]
