# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rect', '0006_add_schedule_seq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='cc_threshold',
            field=models.FloatField(blank=True, default=0.65, verbose_name='切分置信度阈值'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(max_length=64, verbose_name='计划名称'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='reels',
            field=models.ManyToManyField(blank=True, to='rect.Reel'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_no',
            field=models.CharField(blank=True, default='', help_text='自动生成', max_length=64, verbose_name='切分计划批次'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '未激活'), (1, '已激活'), (2, '已过期'), (3, '已作废'), (4, '已完成')], db_index=True, default=0, null=True, verbose_name='计划状态'),
        ),
    ]
