# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import rect.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rect', '0007_auto_20180103_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='LQSutra',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='龙泉经目编码')),
                ('name', models.CharField(max_length=64, verbose_name='龙泉经目名称')),
                ('total_reels', models.IntegerField(blank=True, default=1, verbose_name='总卷数')),
            ],
            options={
                'verbose_name_plural': '龙泉经目管理',
                'verbose_name': '龙泉经目',
            },
            bases=(models.Model, rect.models.TripiMixin),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reel_page_no', models.IntegerField(default=1, verbose_name='卷级页序号编码')),
                ('code', models.CharField(max_length=64, verbose_name='实体藏经页级总编码')),
                ('vol_no', models.CharField(max_length=3, verbose_name='册序号编码')),
                ('page_no', models.CharField(max_length=4, verbose_name='册级页序号编码')),
                ('img_path', models.CharField(max_length=128, verbose_name='图片路径')),
                ('ready', models.BooleanField(default=False, verbose_name='已准备好')),
                ('image_ready', models.BooleanField(default=False, verbose_name='图源状态')),
                ('image_upload', models.BooleanField(default=False, verbose_name='图片上传状态')),
                ('txt_ready', models.BooleanField(default=False, verbose_name='文本状态')),
                ('cut_ready', models.BooleanField(default=False, verbose_name='切分数据状态')),
                ('column_ready', models.BooleanField(default=False, verbose_name='切列图状态')),
                ('s3_inset', models.FileField(blank=True, max_length=256, null=True, storage='storages.backends.s3boto.S3BotoStorage', upload_to='lqcharacters-images', verbose_name='S3图片路径地址')),
            ],
            options={
                'verbose_name_plural': '实体藏经页管理',
                'verbose_name': '实体藏经页',
            },
        ),
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sutra_no', models.CharField(max_length=3, verbose_name='经卷序号编码')),
                ('code', models.CharField(max_length=32, verbose_name='实体藏经卷级总编码')),
                ('ready', models.BooleanField(default=False, verbose_name='已准备好')),
                ('image_ready', models.BooleanField(default=False, verbose_name='图源状态')),
                ('image_upload', models.BooleanField(default=False, verbose_name='图片上传状态')),
                ('txt_ready', models.BooleanField(default=False, verbose_name='文本状态')),
                ('cut_ready', models.BooleanField(default=False, verbose_name='切分数据状态')),
                ('column_ready', models.BooleanField(default=False, verbose_name='切列图状态')),
            ],
            options={
                'verbose_name_plural': '实体藏经卷管理',
                'verbose_name': '实体藏经卷',
            },
        ),
        migrations.CreateModel(
            name='Sutra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=32, verbose_name='实体藏经|唯一经号编码')),
                ('code', models.CharField(max_length=5, verbose_name='实体经目编码')),
                ('variant_code', models.CharField(default='0', max_length=1, verbose_name='别本编码')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='实体经目名称')),
                ('total_reels', models.IntegerField(blank=True, default=1, verbose_name='总卷数')),
                ('lqsutra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rect.LQSutra', verbose_name='龙泉经目编码')),
            ],
            options={
                'verbose_name_plural': '实体经目管理',
                'verbose_name': '实体经目',
            },
            bases=(models.Model, rect.models.TripiMixin),
        ),
        migrations.CreateModel(
            name='Tripitaka',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='实体藏经版本编码')),
                ('name', models.CharField(max_length=32, verbose_name='实体藏经名称')),
            ],
            options={
                'verbose_name_plural': '实体藏经管理',
                'verbose_name': '实体藏经',
            },
            bases=(models.Model, rect.models.TripiMixin),
        ),
        migrations.RemoveField(
            model_name='rect',
            name='page_no',
        ),
        migrations.RemoveField(
            model_name='rect',
            name='reel_no',
        ),
        migrations.RemoveField(
            model_name='rect',
            name='sutra_id',
        ),
        migrations.RemoveField(
            model_name='rect',
            name='vol_no',
        ),
        migrations.AddField(
            model_name='sutra',
            name='tripitaka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sutras', to='rect.Tripitaka'),
        ),
        migrations.AddField(
            model_name='reel',
            name='sutra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reels', to='rect.Sutra'),
        ),
        migrations.AddField(
            model_name='page',
            name='reel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='rect.Reel'),
        ),
    ]
