# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rect', '0008_auto_20180113_0851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charclassifyplan',
            options={'verbose_name': '聚类准备表', 'verbose_name_plural': '聚类准备表管理'},
        ),
        migrations.AlterField(
            model_name='charclassifyplan',
            name='total_cnt',
            field=models.IntegerField(db_index=True, default=0, verbose_name='总数'),
        ),
        migrations.AlterField(
            model_name='charclassifyplan',
            name='wcc_threshold',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4, verbose_name='识别置信阈值'),
        ),
    ]
