# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-19 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rect', '0010_auto_20180118_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reel_task_statistical',
            options={'ordering': ('schedule', '-updated_at'), 'verbose_name': '实体卷任务统计', 'verbose_name_plural': '实体卷任务统计管理'},
        ),
        migrations.AlterField(
            model_name='absenttask',
            name='ttype',
            field=models.PositiveSmallIntegerField(choices=[(2, '置信度'), (1, '顺序校对'), (3, '聚类'), (4, '差缺补漏'), (5, '删框'), (6, '反馈审查')], db_index=True, default=1, verbose_name='切分方式'),
        ),
        migrations.AlterField(
            model_name='cctask',
            name='ttype',
            field=models.PositiveSmallIntegerField(choices=[(2, '置信度'), (1, '顺序校对'), (3, '聚类'), (4, '差缺补漏'), (5, '删框'), (6, '反馈审查')], db_index=True, default=1, verbose_name='切分方式'),
        ),
        migrations.AlterField(
            model_name='classifytask',
            name='ttype',
            field=models.PositiveSmallIntegerField(choices=[(2, '置信度'), (1, '顺序校对'), (3, '聚类'), (4, '差缺补漏'), (5, '删框'), (6, '反馈审查')], db_index=True, default=1, verbose_name='切分方式'),
        ),
        migrations.AlterField(
            model_name='deltask',
            name='ttype',
            field=models.PositiveSmallIntegerField(choices=[(2, '置信度'), (1, '顺序校对'), (3, '聚类'), (4, '差缺补漏'), (5, '删框'), (6, '反馈审查')], db_index=True, default=1, verbose_name='切分方式'),
        ),
        migrations.AlterField(
            model_name='pagetask',
            name='ttype',
            field=models.PositiveSmallIntegerField(choices=[(2, '置信度'), (1, '顺序校对'), (3, '聚类'), (4, '差缺补漏'), (5, '删框'), (6, '反馈审查')], db_index=True, default=1, verbose_name='切分方式'),
        ),
        migrations.AlterField(
            model_name='rect',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间1'),
        ),
        migrations.AlterField(
            model_name='reviewtask',
            name='ttype',
            field=models.PositiveSmallIntegerField(choices=[(2, '置信度'), (1, '顺序校对'), (3, '聚类'), (4, '差缺补漏'), (5, '删框'), (6, '反馈审查')], db_index=True, default=1, verbose_name='切分方式'),
        ),
    ]
