# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-23 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rect', '0011_auto_20180119_2046'),
        ('rect', '0010_auto_20180121_0407'),
    ]

    operations = [
    ]
