# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-23 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rect', '0012_merge_20180123_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rect',
            name='column_code',
        ),
    ]
