# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-27 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rect', '0013_remove_rect_column_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagerect',
            name='reel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reels', to='rect.Reel'),
        ),
    ]
