# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-17 17:35
from __future__ import unicode_literals

from django.db import migrations

def get_sql(filename):
    with open('rect/sql/' + filename) as f:
        return f.read()


class Migration(migrations.Migration):

    dependencies = [
        ('rect', '0003_auto_20180109_2201'),
    ]

    operations = [
        migrations.RunSQL(
            get_sql('bg_create_reel_statis.sql')
        ),

    ]